### ISSUE TITLE
Real 3d

### ISSUE THREAD

**Issue by gedw99** [Jacalz/linedisp#1]
This fake 3d approach is really good for simple stuff . I have seen it extended to allow google earth style apps.

A few weeks ago I was looking into if I could embed a real 3d system into Fyne or gio .

filament looks like a good candidate . It’s designed for speed and physical lighting. You can use it for wireframe or hidden wireframes too. 

The repo produces binaries that can be used on web, desktop and mobile from a golang app.

not sure if your interested in this though

**Comment by Jacalz** [comment]
Thanks a lot for the suggestion. This is however just a bit of a showcase for https://github.com/Jacalz/linalg and how math can be used for this line drawing (especially within Fyne). The idea was based on an exercise that I did for my linear algebra course, so it is more of a proof of concept rather than serving an actual need.
